---

swagger: '2.0'
info:
  title: "Test Go"
  version: 0.3.0
schemes:
  - http
basePath: /api/v0
paths:
  /user/{id}:
    post:
      tags: ["User"]
      operationId: create
      summary: Create test user
      parameters:
        - name: id
          in: path
          description: id
          required: true
          schema:
            type: string
        - name: info
          in: body
          schema:
            $ref: "#/definitions/user"
      responses:
        '200':
          description: created
          schema:
            $ref: "#/definitions/user"
        default:
          description: error
          schema:
            $ref: "#/definitions/error"
definitions:
  user:
    type: object
    required:
      - customerId
      - name
      - surname
      - fipsCode
    properties:
      username:
        type: string
        format: string
      password:
        type: string
        format: string
        minLength: 1
      firstName:
        type: string
        format: string
        minLength: 1
      lastName:
        type: string
        format: string
        minLength: 1
  social_id:
    type: object
    required:
      - ssn
    properties:
      ssn:
        type: string
        format: string
        minLength: 11
  error:
    type: object
    required:
      - message
    properties:
      StatusCode:
        type: integer
        format: int64
      Message:
        type: string
      Token:
        type: string
  principal:
    type: string