---

swagger: '2.0'
info:
  title: "Test Go"
  version: 0.3.0
schemes:
  - http
basePath: /api/v0
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
paths:
  /auth/token:
    get:
      tags: ["Auth"]
      operationId: create
      summary: Create test user
      parameters:
        - name: username
          in: query
        - name: password
          in: query
      responses:
        '200':
          description: created
          schema:
            $ref: "#/definitions/auth"
        default:
          description: error
          schema:
            $ref: "#/definitions/error"
  /list:
    get:
      tags: ["List"]
      security:
        - Bearer: []
      summary: get list
      responses:
        '200':
          description: list
          schema:
            $ref: "#/definitions/auth"
        default:
          description: error
          schema:
            $ref: "#/definitions/error"
  /user:
    post:
      tags: ["User"]
      operationId: create
      summary: Create test user
      parameters:
        - name: info
          in: body
          schema:
            $ref: "#/definitions/user"
      responses:
        '200':
          description: created
          schema:
            $ref: "#/definitions/user"
        default:
          description: error
          schema:
            $ref: "#/definitions/error"
definitions:
  user:
    type: object
    required:
      - customerId
      - name
      - surname
      - fipsCode
    properties:
      username:
        type: string
        format: string
      password:
        type: string
        format: string
        minLength: 1
      firstName:
        type: string
        format: string
        minLength: 1
      lastName:
        type: string
        format: string
        minLength: 1
  list:
    type: object
    properties:
      title:
        type: string
        format: string
      description:
        type: string
        format: string
        minLength: 1
      createdAt:
        type: string
        format: string
  auth:
    allOf:
      - $ref: "#/definitions/user"
      - type: object
        properties:
          token:
            type: string
            format: string
  social_id:
    type: object
    required:
      - ssn
    properties:
      ssn:
        type: string
        format: string
        minLength: 11
  error:
    type: object
    required:
      - message
    properties:
      StatusCode:
        type: integer
        format: int64
      Message:
        type: string
      Token:
        type: string
  principal:
    type: string